name: Build and deploy Node.js app to Azure Web App - WMSTunning

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: wmstunning-deploy
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # para OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- FRONTEND (opcional): solo si existe /client ---
      - name: Build client (if exists)
        run: |
          if [ -d client ]; then
            cd client
            npm ci
            npm run build --if-present
            cd ..
            rm -rf server/public && mkdir -p server/public
            # Copia el build del client según el toolchain que tengas
            if [ -d client/dist ];  then cp -r client/dist/*  server/public/; fi
            if [ -d client/build ]; then cp -r client/build/* server/public/; fi
          fi

      # --- BACKEND: instala con dev para compilar, luego deja solo prod ---
      - name: Install server deps + build (with dev) and prune
        working-directory: server
        run: |
          npm ci
          npm run build --if-present
          npm prune --omit=dev

      # Empaqueta SOLO el server (lo que ejecutará Azure)
      - name: Zip server
        run: |
          cd server
          zip -r $GITHUB_WORKSPACE/app.zip .

      # Login con OIDC (usa tus secretos actuales)
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3252DFCC291441C99EF9162DB3AF6167 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39FC475C67D043EF8C1F99A1DEEEF93D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B12F5CA7B904BFCBCD1D75BE3697847 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WMSTunning'     # EXACTO como en Azure
          package: app.zip           # zip del server
          # NO usar slot-name para producción


          
