name: Build and deploy Node.js app to Azure Web App - WMSTunning

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: wmstunning-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # FRONTEND (opcional, si existe /client)
      - name: Build client (if exists)
        run: |
          if [ -d client ]; then
            cd client
            npm ci
            npm run build --if-present
            cd ..
            rm -rf server/public && mkdir -p server/public
            if [ -d client/dist ]; then cp -r client/dist/* server/public/; fi
            if [ -d client/build ]; then cp -r client/build/* server/public/; fi
          fi

      # BACKEND
      - name: Install server deps + build
        working-directory: server
        run: |
          npm ci --omit=dev
          npm run build --if-present

      - name: Zip server
        run: |
          cd server
          zip -r $GITHUB_WORKSPACE/app.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E264FF2BED9F42DB8368E59BB673BA0E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA629E0CDB474E60BE8DE20EE78A2080 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6BE8805FF86B4C3194207467F6D52477 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WMSTunning'
          package: app.zip
          # NO usar slot-name para producción


