name: Deploy WMSTunning

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: wmstunning-deploy
  cancel-in-progress: true

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect package dir
        id: detect
        shell: bash
        run: |
          if [ -f server/package.json ]; then
            echo "pkgdir=server" >> $GITHUB_OUTPUT
          elif [ -f package.json ]; then
            echo "pkgdir=." >> $GITHUB_OUTPUT
          else
            echo "ERROR: no hay package.json en server/ ni en raíz" >&2
            exit 1
          fi

      - name: Build client (if exists)
        shell: bash
        run: |
          if [ -d client ]; then
            pushd client
            npm ci
            npm run build --if-present
            popd
            RUNTIME_DIR="${{ steps.detect.outputs.pkgdir }}"
            mkdir -p "${RUNTIME_DIR}/public"
            if [ -d client/dist ];  then cp -r client/dist/*  "${RUNTIME_DIR}/public/"; fi
            if [ -d client/build ]; then cp -r client/build/* "${RUNTIME_DIR}/public/"; fi
          fi

      - name: Build runtime
        shell: bash
        run: |
          set -e
          PKGDIR="${{ steps.detect.outputs.pkgdir }}"

          if [ "$PKGDIR" = "server" ]; then
            pushd server
            npm ci
            npm run build --if-present
            npm prune --omit=dev
            test -f dist/index.js || (echo "ERROR: server/dist/index.js no existe" >&2; ls -R dist; exit 1)
            popd
            cd server
            zip -r $GITHUB_WORKSPACE/app.zip .
          else
            npm ci
            npm run build
            npm prune --omit=dev
            rm -rf .release && mkdir -p .release
            cp package.json package-lock.json .release/ || true
            cp -r dist .release/dist
            cp -r node_modules .release/node_modules
            echo "${{ github.sha }}" > .release/dist/version.txt || true
            cd .release
            test -f dist/index.js || (echo "ERROR: dist/index.js no existe" >&2; ls -R dist; exit 1)
            zip -r $GITHUB_WORKSPACE/app.zip .
          fi

      - name: List files to be published
        run: unzip -l $GITHUB_WORKSPACE/app.zip | sed -n '1,200p'

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3252DFCC291441C99EF9162DB3AF6167 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39FC475C67D043EF8C1F99A1DEEEF93D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B12F5CA7B904BFCBCD1D75BE3697847 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WMSTunning'
          package: app.zip
