name: Build and deploy Node.js app to Azure Web App - WMSTunning

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: wmstunning-deploy
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # requerido para OIDC (azure/login)
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- FRONTEND (opcional): solo si existe /client ---
      - name: Build client (if exists)
        run: |
          if [ -d client ]; then
            cd client
            npm ci
            npm run build --if-present
            cd ..
            rm -rf server/public && mkdir -p server/public
            # Copia el build del client según toolchain
            if [ -d client/dist ];  then cp -r client/dist/*  server/public/; fi
            if [ -d client/build ]; then cp -r client/build/* server/public/; fi
          fi

      # --- BACKEND: instala con dev para poder compilar, luego deja solo prod ---
      - name: Install server deps + build (with dev) and prune
        working-directory: server
        run: |
          npm ci
          npm run build --if-present
          npm prune --omit=dev

      # Empaqueta SOLO el server (lo que ejecutará Azure)
      - name: Zip server
        run: |
          cd server
          zip -r $GITHUB_WORKSPACE/app.zip .

      # Login con OIDC (sin publish profile)
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E264FF2BED9F42DB8368E59BB673BA0E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA629E0CDB474E60BE8DE20EE78A2080 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6BE8805FF86B4C3194207467F6D52477 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WMSTunning'   # nombre EXACTO del App Service
          package: app.zip         # zip generado con el server
          # slot-name: staging     # (solo si despliegas a un slot real)





